"""Add duration_hours to drinking_windows

Revision ID: c1dd48ee6059
Revises: f09f295b3e42
Create Date: 2024-11-26 12:32:30.433203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1dd48ee6059'
down_revision: Union[str, None] = 'f09f295b3e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinking_windows', sa.Column('duration_hours', sa.Integer(), nullable=False))
    op.drop_column('drinking_windows', 'start_date')
    op.drop_column('drinking_windows', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinking_windows', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('drinking_windows', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('drinking_windows', 'duration_hours')
    # ### end Alembic commands ###
